// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3v7EBrQSk5tDZl54mjaL6WC7n7h1ibs',
    appId: '1:1003932414576:web:b88e50f7a9e41473fbfab5',
    messagingSenderId: '1003932414576',
    projectId: 'tictoc-clone-haku',
    authDomain: 'tictoc-clone-haku.firebaseapp.com',
    storageBucket: 'tictoc-clone-haku.firebasestorage.app',
    measurementId: 'G-5VH6249JWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDendf8vcYlNi-oZGj4Rzn0ASNU5EJwEOo',
    appId: '1:1003932414576:android:7ddb891b14e2e0a4fbfab5',
    messagingSenderId: '1003932414576',
    projectId: 'tictoc-clone-haku',
    storageBucket: 'tictoc-clone-haku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsw0AG8cRU2ROe9CgPc0zJZtjVJR0_BM',
    appId: '1:1003932414576:ios:2af60a0a314c9664fbfab5',
    messagingSenderId: '1003932414576',
    projectId: 'tictoc-clone-haku',
    storageBucket: 'tictoc-clone-haku.firebasestorage.app',
    iosBundleId: 'com.example.tiktokapp',
  );

}